export const GET_ALL_PRODUCTS = "GET ALL PRODUCTS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET ALL PRODUCTS SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET ALL PRODUCTS FAILURE";

export const ADD_PRODUCT  = "ADD PRODUCT";
export const ADD_PRODUCT_SUCCESS  = "ADD PRODUCT SUCCESS";
export const ADD_PRODUCT_FAIURE  = "ADD PRODUCT_FAILURE";