export const GET_ALL_PRODUCTS = "GET ALL PRODUCTS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET ALL PRODUCTS SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET ALL PRODUCTS FAILURE";

export const ADD_PRODUCT  = "ADD PRODUCT";
export const ADD_PRODUCT_SUCCESS  = "ADD PRODUCT SUCCESS";
export const ADD_PRODUCT_FAIURE  = "ADD PRODUCT_FAILURE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const HANDLE_MODAL = "HANDLE_MODAL";

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";